SCE/SCE/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SCE.Controllers
{
    public class ForumController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

SCE/SCE/Views/Shared/_Layout.cshtml
@using System
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @RenderSection("metaDescription",false)
    @RenderSection("metaKeywords",false)
    <title>sceng.by - @ViewBag.Title -Safety Consult Engineering</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("yandexMap",false)
</head>
<body>
<div class="templatemo-container">
    <div class="col-lg-3 col-md-3 black-bg left-container">
        <div class="menu-mobile">
            <a id="menu-toggle" aria-controls="bs-navbar" aria-expanded="false" class="collapsed navbar-toggle"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
        </div>
        <div class="tm-left-inner-container">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="@Url.Action("Index", "Home")">
                        <img class="img-responsive" src="/Content/images/logo1.png">
                    </a>
                    <hr/>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Home")">Главная </a>
                </li>
                <li class="li-ul">
                    <a href="#" class="toggle-ul">Услуги</a>
                    <ul class="sidebar-nav">
                        <li>
                            <a href="@Url.Action("Outsourcing", "Home")">Аутсорсинг </a>
                        </li>
                        <li>
                            <a href="@Url.Action("SafetyEngineering", "Home")">Охрана труда под ключ</a>
                        </li>
                        <li>
                            <a href="@Url.Action("SOUT", "Home")">СУОТ </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Сounseling", "Home")">Консультирование </a>
                        </li>
                        <li>
                            <a href="@Url.Action("PTM", "Home")">Пожарно-тенический минимум </a>
                        </li>
                    </ul>
                </li>
                <li class="li-ul">
                    <a href="#" class="toggle-ul">Проектирование</a>
                    <ul class="sidebar-nav">
                        <li>
                            <a href="@Url.Action("PPR", "Home")">ППР </a>
                        </li>
                        <li>
                            <a href="@Url.Action("KD", "Home")">КД, КМД</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="@Url.Action("Video","Home")">Видеоматериал</a>
                </li>
                                @*
        <li>
            <a href="@Url.Action("Index","Forum")">Форум</a>
        </li>
                                *@
                <li>
                    <a href="@Url.Action("Contact","Home")">Контакты</a>
                    <hr class="tophr"/>
                </li>
            </ul>
            <!--Footer menu-->
            <div class="footer-menu">
                <div class="soc">
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <a class="circle" target="_blank" href="https://www.facebook.com/groups/307583859603415/?ref=bookmarks">
                            <i class="fa fa-facebook" aria-hidden="true" ></i>
                        </a>
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <a class="circle" target="_blank" href="https://vk.com/public128358401">
                            <i class="fa fa-vk" aria-hidden="true"></i>
                        </a>
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <a class="circle" target="_blank" href="https://ok.ru/group/52963403169924">
                            <i class="fa fa-odnoklassniki" aria-hidden="true" ></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- left section -->
    <div class="col-lg-9 col-md-9 white-bg right-container">
        <div class="tm-right-inner-container">
            <div class="content">
            @RenderBody()
                </div>
            <footer>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 templatemo-copyright">
                    &copy; 2016 safety consulting engineering,
                    ИП Крукович П.С., УНП 192697085
                </div>
            </footer>
        </div>
    </div> <!-- right section -->
</div>	    
    @Html.Partial("_SendMailPopup")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/common")
    @RenderSection("scripts", required: false)
</body>
</html>

SCE/SCE/Views/Shared/_SendMailPopup.cshtml
<div id="send-mail-popup" class="white-popup mfp-hide">
    <h4>Оставьте нам заявку или просто задайте вопрос:</h4>
    <form  action="#" class="form-horizontal sendMailTo">
        <div class="form-group">
            <div class="col-sm-12 col-xs-12 col-md-12 col-lg-12">
                <input type="text" class="form-control" name="name" required placeholder="Имя">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12 col-xs-12 col-md-12 col-lg-12">
                <input type="text" class="form-control" name="phone" required placeholder="+375 (хх) ххх хх хх">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12 col-xs-12 col-md-12 col-lg-12">
                <input type="email" class="form-control" name="mail" required placeholder="Email">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12 col-xs-12 col-md-12 col-lg-12">
                <textarea rows="5" class="form-control" name="message" required placeholder="Сообщение"></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12 col-xs-12">
                <button type="submit"  class="btn btn-default sendMailToServer">Отправить <i class="fa fa-arrow-circle-right" aria-hidden="true"></i></button>
            </div>
        </div>
    </form>
</div>


<div id="success" class="white-popup mfp-hide">
    <h4>Заявка успешно отправлена!</h4> 
<p>С вами свяжуться в течении нескольких минут.</p>
</div>

<div id="success" class="white-popup mfp-hide">
    <h4>Произошла ошибка отправки!</h4>
    <p>Пожалуйста, попробуйте повторно отправить сообщение</p>
</div>